export const ADD_CONTACT = "PHONEBOOK/ADD_CONTACT";
export const EDIT_CONTACT = "PHONEBOOK/EDIT_CONTACT";
export const DELETE_CONTACT = "PHONEBOOK/DELETE_CONTACT";
export const SELECT_CONTACT = "PHONEBOOK/SELECT_CONTACT";
export const DELETE_SELECTED_CONTACTS = "PHONEBOOK/DELETE_SELECTED_CONTACTS";

export const FETCH_COVID = "COVID/FETCH_COVID";
export const REQUEST_COVID = "COVID/REQUEST_COVID";

export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
